version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: manoeuvreerspel-backend
    container_name: manoeuver_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - manoeuvreerspel-network

  nginx:
    image: nginx:alpine
    container_name: manoeuver_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - manoeuvreerspel-network

networks:
  manoeuvreerspel-network:
    driver: bridge
